### ISSUE TITLE
SourceScaner.cc

### ISSUE THREAD

**Issue by VectorFury** [samuelkgutierrez/dflow#1]
Dear Sir 
      When I compiled this prpject, i found it need SourceScanner.cc file, it is a mistake?How can I compile it correctly?  best wishes for you.

**Comment by samuelkgutierrez** [comment]
Hello,

I just fixed a bunch of build issues in the following commit: a5823bd9de42d0bdfe9a751acf3c9479d851eee9. Can you pull the latest source and try again?

By the way, `SourceScanner.cc` is automatically generated from the source located in `SourceScanner.ll` by `flex`.

**Comment by VectorFury** [comment]
It works now !!! thank you so much.

**Comment by samuelkgutierrez** [comment]
Excellent. You're welcome.
